apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ezrg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ezrg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ezrg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ezrg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ezrg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yryy-tenant/rhtap-demo-app/hacbs-test-project-ezrg@sha256:81c52c7de10f4ce56815365eb145244b5893ab6eda2cc6a68e50d8e42d42e861
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
